steps:
  # 1. Build Backend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tei-backend', './backend']

  # 2. Push Backend Image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tei-backend']

  # 3. Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tei-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tei-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      # NOTE: Environment variables like DB credentials should be set in Cloud Run UI or via Secret Manager

  # 4. Install Frontend Dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    dir: 'frontend'

  # 5. Build Frontend
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'frontend'
    env:
      - 'VITE_API_URL=https://tei-backend-uc.a.run.app' # Placeholder, update after first backend deploy

  # 6. Deploy Frontend to Firebase (Optional, requires token)
  # - name: 'gcr.io/$PROJECT_ID/firebase'
  #   args: ['deploy', '--only', 'hosting']

images:
  - 'gcr.io/$PROJECT_ID/tei-backend'
